---
- name: update cashe
  apt: update_cache=yes
- name: Install Nginx
  apt: name=nginx state=present
- name: Change file Index.html
  copy: src=index.html dest=/var/www/html/index.html force=yes owner=root group=root mode="u=rwx,g=rx,o=rx"
- name: Restart nginx
  service: name=nginx state=restarted enabled=yes
- name: Waits for port 80 of any IP to close active connections, don't start checking for 10 seconds
  wait_for: port=80 delay=10 state=present
