---
- hosts: all
  tasks:
    - name: Install nginx package
      apt: name=nginx state=present
      become: yes
    - name: Starting nginx service
      service: name=nginx state=started enabled=yes
      become: yes
