---
- name: Update apt cache
  apt:
    update_cache: yes
- name: Install gnupg, apt-transport-https
  apt:
    name:
      - apt-transport-https
      - gnupg
    state: present
- name: Install elasticsearch package
  apt:
    deb: "{{ package_source }}"
    update_cache: yes
- name: Copy file elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
    force: yes
- name: reload elasticsearch
  systemd:
    daemon_reload: true
    name: elasticsearch.service
    state: started
- name: restart elasticsearch
  systemd:
    name: elasticsearch.service
    state: restarted
    enabled: yes
