---
- name: update cashe
  apt:
    update_cache: yes
- name: Add zabbix repository from https://www.zabbix.com.
  apt:
    deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
    update_cache: yes
- name: Install zabbix-agent
  apt:
    name: zabbix-agent
    update_cache: yes
    state: present
- name: change file /etc/zabbix/zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server=127.0.0.1$'
    line: Server={{ zabbix_int_ip }}
- name: change file /etc/zabbix/zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^ServerActive=127.0.0.1$'
    line: ServerActive={{ zabbix_int_ip }}
- name: change file /etc/zabbix/zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Hostname=Zabbix server$'
    line: Hostname={{ ansible_hostname }}
- name: change file /etc/zabbix/zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^# HostMetadata=$'
    line: HostMetadata=Linux servers
- name: Restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
- name: Start zabbix-agent and make zabbix-agent enabled
  service:
    name: zabbix-agent
    state: started
    enabled: yes
