---
- name: Update cashe
  apt:
    update_cache: yes
- name: Add zabbix repository from https://www.zabbix.com.
  apt:
    deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
    update_cache: yes
- name: Install postgresql pip apache2 zabbix-server-pgsql zabbix-frontend-php php8.1-pgsql zabbix-apache-conf zabbix-sql-scripts acl python3-psycopg2
  apt:
    name:
      - postgresql
      - pip
      - apache2
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php8.1-pgsql
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - acl
      - python3-psycopg2
    state: present
    update_cache: yes
- name: Start postgresql
  service:
    name: postgresql
    state: started
    enabled: yes
- name: Start apache2
  service:
    name: apache2
    state: started
    enabled: yes
- name: Start zabbix-server
  service:
    name: zabbix-server
    state: started
    enabled: yes
- name: Create user zabbix
  become_user: postgres
  postgresql_user:
    name: zabbix
    password: "{{ password_DB }}"
- name: Create database zabbix
  become_user: postgres
  postgresql_db:
    name: zabbix
    owner: zabbix
- name: Import scripts
  shell: zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix
- name: Change file /etc/zabbix/zabbix_server.conf
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^# DBPassword='
    line: DBPassword={{ password_DB }}
- name: Restart zabbix-server
  service:
    name: zabbix-server
    state: restarted
- name: Restart apache2
  service:
    name: apache2
    state: restarted
- name: Copy file zabbix.conf.php
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    force: yes
    owner: www-data
    group: www-data
    mode: "u=rw"
- name: Send request to Zabbix API
  uri:
    url: "http://localhost/zabbix/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: application/json-rpc
    body: "{{ lookup('file', 'zabbix-token-request.json') }}"
    body_format: json
  register: token_response
- name: Add zabbix-token to ansible facts
  set_fact:
    zabbix_token: "{{ token_response.json.result }}"
- name: Send action create request to Zabbix API
  uri:
    url: "http://localhost/zabbix/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: application/json-rpc
    body: "{{ lookup('template', 'zabbix-create-action-request.json.j2') }}"
    body_format: json
  register: action_response
- name: Send dashboard create request to Zabbix API
  uri:
    url: "http://localhost/zabbix/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: application/json-rpc
    body: "{{ lookup('template', 'zabbix-create-dashboard.json.j2') }}"
    body_format: json
    status_code: 200
  register: dashboard_response
- name: install zabbix-agent
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes
- name: Restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes
